### PR TITLE
Make modelica-mode MELPA conform

### PR DESCRIPTION
**Pull request by rudi**
This pull request should bring modelica-mode up to the requirements for inclusion into MELPA.

- Remove XEmacs compatibility code
- Redefine a key sequence (`C-c C-h`) that is reserved by emacs, and redefine `C-c M-h` for reasons of symmetry
- Rename all variables and functions to begin with `modelica-` instead of `mdc-`
- Adjust most docstrings to conform to `checkdoc`'s requirements
- Add a github workflow that checks all pushes against `checkdoc` and `package-lint`

Additionally, make some indentation-related variables customizable.

### CODE REVIEW

**Comment by rudi** [comment]
After this pull request, a version upgrade to 1.5 would be warranted.  I think the code is more or less ready to be reviewed by the MELPA maintainers.

**Comment by dietmarw** [comment]
I'd say the number of changes (also the renaming of variables) justifies a bump in the major version number to version `2.0.0`.

**Comment by dietmarw** [comment]
@rudi Could you update the ChangeLog file as part of this PR? Just summarize the most important changes. Details can always be pulled from the git log for the specially interested.

**Comment by rudi** [comment]
> @rudi Could you update the ChangeLog file as part of this PR? Just summarize the most important changes. Details can always be pulled from the git log for the specially interested.

Sure, done :)

**Comment by dietmarw** [comment]
> Sure, done :)

And even with iso-date, nice!

**Pull request merged**
