### PR TITLE
Make README prettier

### PR DESCRIPTION
**Pull request by rudi**
- Low-effort conversion to markdown

### CODE REVIEW

**Comment by rudi** [comment]
I did not make any content changes; maybe https://github.com/modelica-tools/modelica-mode/issues/1 could be mentioned (i.e., OO-Browser being unmaintained)

**Comment by dietmarw** [comment]
I agree, a mention that the oo-browser is outdated, and hence the whole section might be good.

**Comment by rudi** [comment]
I think the best way forward would be to move everything oo-browser-related to a new file `README-oo-browser`, and leave the documentation for `modelica-mode.el` in `README.md`.  If you agree, I could add that to the pull request; just let me know.

**Comment by dietmarw** [comment]
Sure, go ahead. I'm just glad somebody is actively using this extension and any improvement is good.

**Comment by rudi** [comment]
Now done, and fixed the installation instructions a bit as well (the `auto-mode-alist` example was subtly wrong; it matched any filename ending in `mo` of length 3 or longer).

**Comment by dietmarw** [comment]
Maybe it would still be good to at least reference `README-oo-browser.md` in the main `README.md` (including a note on the unmaintained status). What do you think?

**Comment by rudi** [comment]
Good idea; done and fixed a link to the oo-browser code while I was there.

**Review by dietmarw — APPROVED** [review]
This looks good now. I'm always amazed to see source-forge still exists ;-)

**Comment by dietmarw** [comment]
@rudi Given your improvements in #5, #6, #7 maybe it would be good to have a new tagged version `1.5.0`?

**Comment by rudi** [comment]
Sounds good, but let me add some other changes first, like a proper package header so the mode can be added to melpa.

**Comment by rudi** [comment]
Do we want to update the changelog?  Or maybe switch to the https://keepachangelog.com/en/1.0.0/ format?

**Comment by dietmarw** [comment]
I would keep it simple and not spend too much time on the ChangLog. So a simple update should be sufficient.

**Pull request merged**
